### ISSUE TITLE
How do I make the output text editable?

### ISSUE THREAD

**Issue by 21Machines** [marduk191/ComfyUI-Fluxpromptenhancer#7]
How do I make the output text editable?

Got this working on my macOS ComfyUI install so that 's saying something.  Thank you.

Consider a "Prefix" entry in the base node, so we can drop in the LoRA trigger word.

Also works well on my RunPod installation.

**Comment by marduk191** [comment]
use the chibi-nodes text box, it has a passthrough option for doing edits, i don't plan on doing it  since there are multiple node pack that can do it already..
