### ISSUE TITLE
data did not match any variant of untagged enum PyPreTokenizerTypeWrapper at line 951 column 3

### ISSUE THREAD

**Issue by reydeljuego12345** [marduk191/ComfyUI-Fluxpromptenhancer#8]
All have this error, this node is broken try installing updates for comfy to replicate, seems like the tokenizer of the LLM cannot enum cause there are not data imput.

**Comment by marduk191** [comment]
I don't have time to work on it now. I'll check it out this weekend

**Comment by marduk191** [comment]
updated today and i can't replicate the error, must be your configuration.

**Comment by marduk191** [comment]
![image](https://github.com/user-attachments/assets/62bcdc92-a907-457a-96ea-45334d90e186)
